export const playersData = [
    "Ayyoub",
    "Vincent",
    "Nicolas L",
    "Charles Henri",
    "Nada",
    "Emeline",
    "Mickael",
    "Mathilde",
    "Stéphane",
    "Adam",
    "Cyril",
    "Hugo",
    "Corentin R",
    "Corentin P",
    "Aurélien",
    "Marie",
    "Nicolas P",
    "Florent",
    "Pascal"
]